### ISSUE TITLE
bugged `arch-install-script` break chroot build

### ISSUE THREAD

**Issue by bartoszek** [AladW/aurutils#1015]
Just for information, if someone was looking for cause of the error in chroot build init, like I was for last hour:
There's a problem with latest `systemd` breaks `pacstrap(arch-install-scripts)` used by `mkarchroot(devtools)`
https://bugs.archlinux.org/task/75378
https://github.com/archlinux/arch-install-scripts/issues/21

**Comment by AladW** [comment]
The reports mention the issue is fixed.

With problems like this it might be worth investigating how much functionality of `pacstrap` is actually needed for `aur-chroot` (#909). The gist of it is https://github.com/archlinux/arch-install-scripts/blob/master/pacstrap.in#L103-L131, and options can be adjusted to what `aur-chroot` requires instead of exposing them on the command-line.
