### ISSUE TITLE
`--makepkg-conf=FILE` broken for chroot builds

### ISSUE THREAD

**Issue by VorpalBlade** [AladW/aurutils#1034]
It appears that the `aur chroot` copies the makepkg.conf pointed to with `--makepkg-conf=FILE`  to `/var/lib/aurbuild/x86_64/root/etc/makepkg.conf` correctly. However, it is overwritten with the host `/etc/makepkg.conf` in `/var/lib/aurbuild/x86_64/<user>/etc/makepkg.conf`. I don't understand how this happen, but here are some steps to reproduce:

```console
$ cp /etc/makepkg.conf /tmp/makepkg-temp.conf
$ # Edit /tmp/makepkg-temp.conf to have observable difference, eg. different PACKAGER line
$ aur build --clean --syncdeps --chroot --force --makepkg-conf=/tmp/makepkg-temp.conf aurutils
$ sudo pacsync custom
$ pacman -Si aurutils
$ # Note details indicating it was built with /etc/makepkg.conf, not your custom one.
```

If we investigate further we will see that our custom makepkg.conf was copied into `/var/lib/aurbuild/x86_64/root` but not `/var/lib/aurbuild/x86_64/<username>`.

[aurutils.log](https://github.com/AladW/aurutils/files/9741375/aurutils.log)

**Comment by VorpalBlade** [comment]
After reading through the code of makechrootpkg it seems it copies `PACKAGER` from the host. However this issue also affects non-copied variables such as `CFLAGS`: The reason I found out about this was due to `-march` not taking effect when compiling for an old computer that doesn't support `x86_64-v3` (which my main `makepkg.conf` is set to use, but my specialized `makepkg-compat.conf` does not use).

**Comment by AladW** [comment]
The user copy should not require explicit copying, its contents are `rsync`'d from the root: https://gitlab.archlinux.org/archlinux/devtools/-/blob/master/src/makechrootpkg.in#L101

`MAKEFLAGS` and `PACKAGER` are indeed taken from the host: https://gitlab.archlinux.org/archlinux/devtools/-/blob/master/src/makechrootpkg.in#L167-172

This is yet another design flaw in `devtools`. A possible workaround is force `MAKEFLAGS` and `PACKAGER` in the `makechrootpkg` environment, but then `aur-chroot` has to source or manually parse any supplied `makepkg.conf`. Sourcing is a can of worms because `aur-chroot` only has privileged commands, but sourcing a user-supplied file should be done unprivileged.

Parsing would look similar to `aur(1)`'s environment file:
```bash
while IFS=' = ' read -r key value; do
    case $key in
	MAKEPKG|PACKAGER) 
            printf -v "$key" '%s' "$value"
            export "${key?}" ;;
    esac
done < <(pacini "$makepkg_conf")
wait "$!"

sudo --preserve-env=GNUPGHOME,SSH_AUTH_SOCK,PKGDEST,MAKEPKG,PACKAGER makechrootpkg ...
```

**Comment by AladW** [comment]
This is something I might address in a standalone version of `aur-chroot`. In the devtools version, however, I don't think adding workarounds is worth it.
