### ISSUE TITLE
aurutils remote-repo?

### ISSUE THREAD

**Issue by misterhsp** [AladW/aurutils#1071]
Is it possible to use aurutils with a remote repo (https on my home server)?

Thanks ...

**Comment by AladW** [comment]
The easiest is to run `aurutils` itself on the home server, where the repo is configured as `file://`, and `https://` on the clients. Otherwise you need to set up something that sends the built packages and updated database from the build client to the server, e.g. `sshfs` or `rsync`.

Related: https://github.com/AladW/aurutils/blob/master/man7/aurhosting.7

**Comment by misterhsp** [comment]
Am 20.05.23 um 19:13 schrieb Alad Wenter:
>
> The easiest is to run |aurutils| itself on the home server, where the
> repo is configured as |file://|, and |https://| on the clients.
> Otherwise you need to set up something that sends the built packages
>
Yes, I know. But is not possible. My home server runs Debian. Might be
an idea for future version (remote-repo).

**Comment by AladW** [comment]
In the long term I'd like `aurutils` to work outside Arch, but this requires a completed rewrite of `aur-chroot` (#909). Until then you can also use the included `Dockerfile`.
