### ISSUE TITLE
Help getting started: Where do I even begin?

### ISSUE THREAD

**Issue by evaryont** [AladW/aurutils#247]
So I have my laptop with a variety of packages from the AUR, but I felt that possibly starting with an empty repository would be easier. But I don't even know how to do that.

* Where do I start? Is it making the repository, or is that handled by aurutils for me?
* I've read `aurutils(7)` which implies that once that repository is made, I just use aursync instead of makepkg. Is that correct?
* Is there any utility for sharing the custom repository? I have a number of machines at home running Arch, along with servers on the internet. Do I build everything on my laptop and then copy the local repository to my web server?

I'm just looking at the utilities an I'm overwhelmed, I guess. I'd appreciate a clear, step by step "beginners tutorial" or getting started document to guide me. (And there are two obvious [to me] places to start; either from a freshly installed machine with nothing but base installed, or after a user as lived in Arch for a while and has pulled in any number of packages.)

**Comment by djmattyg007** [comment]
There used to be some "getting started" instructions in the readme a long time ago. I'm not sure what happened to them, but I agree that it would be good to see them return.

**Comment by AladW** [comment]
The getting started instructions were merged to aurutils(7), which consists of:
* Summary of aurutils programs
* Configuring a local repository
* Example usage of aurutils programs

So, this is where you start. It should be clear that a repository is not configured automatically from the instructions how to configure one manually, but this can be made more explicit if required

>I've read aurutils(7) which implies that once that repository is made, I just use aursync instead of makepkg. Is that correct?

Depends on what you want to do. `aursync` is an aur helper in the classical sense, but you can create your own helper or workflow from the other scripts such as `aurchain`. 

In particular, the aurutils `makepkg` equivalent is `aurbuild`, which handles updating the local repository, chroot builds and package signing transparently.

>Is there any utility for sharing the custom repository? I have a number of machines at home running Arch, along with servers on the internet. Do I build everything on my laptop and then copy the local repository to my web server?

You can use darkhttpd or any http server you prefer. A while back, I've started updating the wiki instructions:

https://wiki.archlinux.org/index.php/User:Alad/Local_repository

The update is incomplete, but it looks like the direction you're looking for.

>(And there are two obvious [to me] places to start; either from a freshly installed machine with nothing but base installed, or after a user as lived in Arch for a while and has pulled in any number of packages.)

Well, you can at least assume base-devel since anyone who installed Arch the regular way (via the wiki instructions) will be notified of its importance in building packages. Personally when I have a new arch install, I just open up aurutils(7) and copy paste the config snippets for the repository, then start using aursync.

**Comment by Earnestly** [comment]
> Is there any utility for sharing the custom repository? I have a number of machines at home running Arch, along with servers on the internet. Do I build everything on my laptop and then copy the local repository to my web server?

Just to expand on this beyond what @AladW said, there is also the opportunity to host pacman repos on places like github or gitlab, for example:

```
[earnestly]
# You will want to be using package signing here, but this is only a proof of
# concept
SigLevel = PackageOptional
Server = https://raw.githubusercontent.com/Earnestly/earnestly/master
```

Other templates:

```sh
https://gitlab.com/$user/$repo/raw/${commit:-master}
https://try.gogs.io/$user/$repo/raw/${commit:-master}
http://repo.or.cz/$repo.git/blob_plain/${commit:-HEAD}:
https://raw.githubusercontent.com/$user/$repo/${commit:-master}
```

**Comment by djmattyg007** [comment]
Please don't underestimate the importance of having some "getting started" advice in the readme. It will make everything seem much more approachable. At the very least include a pointer to the relevant man page which contains more details.

**Comment by djmattyg007** [comment]
I know there is a reference to aurutils(7) in the readme, but I really do think it would be a good idea if it was moved into a dedicated "getting started" section.

Just my two cents. I always prefer more explicit documentation.

**Comment by AladW** [comment]
The difference between "usage" and "getting started" is imo purely semantical, though former term is more common e.g. on ArchWiki. Otherwise "usage" also points to the various section 1 manuals, which are further summarized in aurutils(7).

I might merge some parts of the README with aurutils(7), but the bulk of the information (i.e., the general topic of local repositories) should be in the linked wiki article. Including handy tricks such as the github hosting @Earnestly mentioned.

**Comment by AladW** [comment]
Add main points to #217.
