### ISSUE TITLE
Patch PKGBUILD

### ISSUE THREAD

**Issue by ashkitten** [AladW/aurutils#250]
I was wondering if there exists the functionality to patch a PKGBUILD, maybe using customizepkg? Or is this a planned feature?

**Comment by AladW** [comment]
I had some logic in place to keep local changes with `git stash`, however that didn't seem to work reliably so I switched back to `git reset` (which is however only run if there are remote changes). Since `aurfetch` is now a short, separate script it's easy to drop in your own version that uses e.g. `git rebase`. Personally I just run `aurbuild` if I fork my own PKGBUILDs from AUR.

**Comment by Earnestly** [comment]
Isn't this merely a pipeline question again?  Read a list of packages, if it matches some case statement, apply whatever action you wish and continue.  It shouldn't be necessary for aurutils to implement any of this directly since it provides the tools to do it ones self, imo.
