### ISSUE TITLE
aur-sync: making it installed-package-aware

### ISSUE THREAD

**Issue by terencode** [AladW/aurutils#303]
Aurutils should first check if the queried package is already added to one or more databases and be smart about it:

- When updating an existant package without specifying the repo: <code>aur sync <i>pkgname</i></code>
    1. Find the repository associated to the package
    2. Update the package using its actual repository

- When installing an existing package in a different repository:  <code> aur sync <i>pkgname</i> --repo=<i>repo1</i> && aur sync <i>pkgname</i> --repo=<i>repo2</i></code>
    1. Compare the repositor(y/ies) associated to the package with the specified repository
    2. - A match is found: ask to confirm you want to add the package to this repository
        - No match is found: this is a new package; do not ask anything; fetch the package

**Comment by djmattyg007** [comment]
I'm not sure your first point makes sense. It sounds like it assumes that the repository is always actually in use by pacman on the same host on which it is hosted.

**Comment by terencode** [comment]
@djmattyg007 how do you do when when the host is different?

**Comment by AladW** [comment]
"smart" sounds like it would be complex and be prone to edge cases. In the first bullet you could have:

- packages specified on the command line that are in a single, none, or multiple different repositories
- packages specified on the command line that are in a remote repository, for example any of the Arch Linux repositories
- the implication that the repository database as it is on disk and as seen by pacman are the same, which is often not the case (e.g., for container builds)

The second bullet implies adding interaction which, apart from the inspection step with `vifm`, I'd like to avoid. Since this appears independent from `aur-sync`, you could likely implement it in some separate script which queries local repositories and runs `aur-sync` afterwards.

**Comment by terencode** [comment]
@AladW what approach would you take? I clearly see it will be very complicated to handle all possible cases so it should limit to things worth doing to improve usability.

**Comment by AladW** [comment]
I'd leave out the first bullet for the above reasons and because IMO these things should be left to the user. The second could be implemented with `aur-rfilter`, compare #165.

**Comment by AladW** [comment]
In practice:
```
candidate=$(aur rfilter -d "$repo" "$pkg")
if [[ $candidate ]]; then
  msg "$pkg is already satisfied in [$repo]"
  # additional steps here
  exit
fi
```
So I think this is another one for the big list in #20.

**Comment by AladW** [comment]
Added to #217.
