### ISSUE TITLE
Github: add one badge per different aur utils

### ISSUE THREAD

**Issue by terencode** [AladW/aurutils#307]
This should make it easier to categorize/manage what util the issues are focused on.
Create badges for at least: 
- build
- sync
- search
- fetch
- vercmp
- deps
- rpc
- pkglist

**Comment by AladW** [comment]
Phew, that's 8 new labels! Is it much better than simply having the script name in the title? For example, typing `sync` in the search shows most results for `aur-sync`.

**Comment by terencode** [comment]
@AladW I don't know, I thought it could have been useful to properly highlight which util the issue is dealing with (with github you can then filter by label) :stuck_out_tongue:

**Comment by AladW** [comment]
Impressive. In any event the main effort would be in relabeling all existing issues (over 300 by now)...

**Comment by terencode** [comment]
@AladW I get you, that was just a suggestion if it does not help much compared to the amount of work needed, let's give up :)

**Comment by AladW** [comment]
Thanks for understanding ;)

**Comment by maximbaz** [comment]
a bit off-topic, but could you choose different colors for `documentation` and `enhancement` labels? 😀

**Comment by AladW** [comment]
@maximbaz I missed this suggestion. Would color would give `documentation`? I thought it as a kind of "enhancement" too, so I gave both labels the same color.

**Comment by maximbaz** [comment]
Any unused color, I guess — I suggested that only because for me personally a ticket with `enhancement` label means that I will get a new shiny feature in aurutils once it is closed (so it's an attractive ticket to follow), but a ticket with `documentation` means that something we discussed in comments needs to end up in manual, but since I have already read the comments and have the knowledge, I'm not as eagerly waiting to see it closed 🙂

**Comment by AladW** [comment]
>enhancement label means that I will get a new shiny feature 

Well, to me "enhancement" means "improve an existing feature or general usability", "feature" means "add yet another command line switch or new script". I concur that documentation is more stale though, so I'll change it.
