### ISSUE TITLE
aur-build: ask to import GPG key

### ISSUE THREAD

**Issue by FunctionalHacker** [AladW/aurutils#434]
Just migrated my repo to another server and decided to rebuild all of my packages and I noticed it's quite a hassle, especially when building multiple packages. to import all of the GPG keys by hand. So, I'm asking you to add a feature that asks the user if they want to import the missing key.

**Comment by maximbaz** [comment]
You are probably looking for `keyserver-options auto-key-retrieve` option, add this to your `~/.gnupg/gpg.conf`.

**Comment by ReekyMarko** [comment]
Aah did not know of this option, thanks!

**Comment by AladW** [comment]
No wonder: https://wiki.archlinux.org/index.php?title=Makepkg&diff=510044&oldid=510043

**Comment by JulianKniephoff** [comment]
Is there any chance of reconsidering adding something like this? Maybe even an automated version? `auto-key-retrieve` unfortunately does not work (anymore) for some signatures in the AUR, most notable for me the Dropbox one, because they don't contain the fingerprint of the key, but only the key ID, which [`gpg` doesn't use for lookup during `auto-key-retrieve` anymore](https://dev.gnupg.org/rG96bf8f477805bae58cfb77af8ceba418ff8aaad9).

See also [this Q&A](https://unix.stackexchange.com/questions/616160/gpg-recv-keys-works-but-auto-key-retrieve-does-not/) I have been grappling with the last couple of days. :sweat_smile:

**Comment by AladW** [comment]
Dear lord, I can stand GPG less every day.
