### ISSUE TITLE
aur-build: fails to install dependencies with conflicts

### ISSUE THREAD

**Issue by icewind1991** [AladW/aurutils#447]
When trying to install [dqlite](https://aur.archlinux.org/packages/dqlite) in chroot it fails to install the `sqlite-replication` dependency because this conflicts with `sqlite` from the base image.

It would make sense to automatically accept replacements of conflicting packages as long as the replacements provides the original.

Tested with both the latest release and master.

debug output:

```
resolving dependencies...
looking for conflicting packages...
:: sqlite-replication and sqlite are in conflict. Remove sqlite? [y/N] error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependencies)

:: sqlite-replication and sqlite are in conflict
==> ERROR: 'pacman' failed to install missing dependencies.
==> ERROR: Build failed, check /var/lib/aurbuild/x86_64/robin/build
```

**Comment by DamienRobert** [comment]
@AladW: there is a trick to make `makepkg` pass options to pacman other than the ones supported natively (like --noconfirm, --noprogress). Indeed, `makepkg FOO=foo` will set 'FOO' to 'foo' (see `extra_environment`, so you can pass use `makepkg PACMAN_OPTS=--confirm` for instance. And since `makechrootpkg` pass its extra arguments to `makepkg`, you could do `makechrootpkg -- 'PACMAN_OPTS=--confirm'` (or `--ask=4` or whatever) to override the `--noconfirm` default of `makechrootpkg`. 

Two drawbacks: `extra_environment` does not support arrays, so you cannot use `makepkg PACMAN_OPTS+=(foo bar)` to append pacman options, and so you can only set one pacman option. You could also use this feature to overwrite the internal variables of makepkg (to override the defaults of makechrootpkg), but these variables will then be exported, which is annoying.

**Comment by AladW** [comment]
Since `--ask` has problems of its own, the proper solution would be for `devtools` to not include `--noconfirm` in its default arguments. Until that happens, I'd say the documentation https://github.com/AladW/aurutils/blob/master/man1/aur-chroot.1#L102-L113 is a good compromise. Thanks for the input.
