### ISSUE TITLE
aur-build: fails with multilib dependent package

### ISSUE THREAD

**Issue by bartoszek** [AladW/aurutils#449]
`aurutil` by default uses `/usr/share/devtools/pacman-extra.conf` witch renders packages having deps in multilib repository to fail. We could use the `pacman-multilib.conf` instead and have them working with minimum effort.
On the other hand, we could exercise some more :smirk:  and create a custom subroutine to check deps list:
```
# detect multilib package
readonly is_pacman_conf_multilib=$(
    for pkg in $(source PKGBUILD 2>/dev/null; echo ${depends[@]})
        do expac -S %r $pkg
    done|grep -q multilib
    echo $?
)
# set pacman_conf_default
pacman_conf_default="/usr/share/devtools/pacman-$( ((is_pacman_conf_multilib)) && echo "extra" || echo "multilib").conf"

 # baseline configuration
readonly pacman_conf=${pacman_conf-${pacman_conf_default}}
```

**Comment by AladW** [comment]
Late response... is there anything speaking against always enabling `multilib`?

**Comment by eli-schwartz** [comment]
This makes aurutils more fragile than it has to be. Specifically, it means that aurutils won't work on CPU ports that don't have a multilib concept. You'll just get a database sync error because multilib doesn't exist on the mirror, and then pacman will exit with a fatal error.

**Comment by AladW** [comment]
That makes me wonder, why does devtools32 still have multilib file in their repository? https://git.archlinux32.org/archlinux32/devtools32/src/branch/master/pacman-multilib.conf

**Comment by eli-schwartz** [comment]
Because devtools32 is the build toolchain for the archlinux32 project, so they install devtools32 on the build *hosts*... which are archlinux.org x86_64 systems. It shouldn't be a problem as long as people don't manually try to run multilib-build -- or use the pacman-multilib.conf -- on a 32-bit system.

This is no different from the historic state of archlinux.org i686 repositories prior to November 2017.

...

This issue was initially discovered by IRC user "Xogium" on an archlinux-arm system. archlinux-arm packages devtools-alarm as the upstream devtools release tarball with a handful of patches to makechrootpkg and arch-nspawn, but doesn't otherwise modify or strip out the archbuild configs.

**Comment by AladW** [comment]
This sort of thing makes me regret supporting anything but Arch proper. I guess we can revert to `pacman-extra.conf` and either:
1. leave `multilib` entirely to the user;
2. add a `--multilib` switch which sets `pacman-multilib.conf` and installs the required multilib packages to the chroot;
3. as 2, but check $0.

The last approach is what `archbuild` does, but it's not very enticing just to handle one use-case.

**Comment by eli-schwartz** [comment]
4) Do as suggested initially by @bartoszek and check if any of the packages in make/depends=() are prefixed with "lib32-" (or use expac with the assumption the user has enabled multilib).
5) `if pacman-conf --repo-list| grep -q multilib; then echo "using multilib-enabled chroot to match host"; fi`

Honestly, this should always have been the approach.

BTW 5) would mean that users who try to aur-sync a multilib package when their pacman.conf does not enable multilib, see immediate breakage when trying to build the package rather than only once they built it, then try to pacman -Syu it from their aurutils custom repo. This may be desirable to show immediate errors for users syncing packages to their own machine, or undesirable if users are using aurutils to generate custom repos purely meant for other machines and don't happen to have multilib enabled on their build bot or whatever.

**Comment by Earnestly** [comment]
Are you concerned about users who have enabled it (and thus passes the `grep -q` check) but yet to sync the remote databases?

Perhaps checking for the existence of databases might be more meaningful?, e.g.

```sh
dbpath=$(pacman-conf DBPath)

while IFS= read -r repo; do
    if [[ ! -e $dbpath/sync/$repo.db ]]; then
        error "$argv0: $repo: repository available but has no $dbpath/sync/$repo.db"
        exit 1
    fi
done < <(pacman-conf -l)
```

**Comment by AladW** [comment]
These things are now entirely up to the user and how he decides to use `devtools`: #591

**Comment by artkpv** [comment]
I've just tried aur utils. Set up custom repository as described in `man aur`. Successfully done `pacman -Syu` after it. But now it breaks with this:

```
[I] ➜ aur sync -c python-azure-cli

# ... there goes git clonning etc... 

error: config file /usr/share/devtools/pacman-multilib.conf could not be read: No such file or directory
error parsing '/usr/share/devtools/pacman-multilib.conf'
sudo: mkarchroot: command not found

```

So pacman-multilib should be enabled somehow? It should be always for using aur utils?

**Comment by AladW** [comment]
Please read the `optdepends` and install `devtools`.
