### ISSUE TITLE
Suggestion on additional configuration

### ISSUE THREAD

**Issue by Gfurst** [AladW/aurutils#457]
May I suggest some additional config options? And in case there is an existing workaround, please do let me know.

1. The option to not actually straight up install said recently built package, just move it to the repository and update the database, as its not always you want that specific package installed in the current build system.
2. I particularly fail to see the point of showing us the listed files, as opposed to for example preview the make file, in case you want change a setting or so, in any case I'd suggest making that preview optional, since its a unneeded interaction.

**Comment by maximbaz** [comment]
Hi there 👋 

1. Are you sure this actually happens? In any case, build in chroot and aurutils will not touch your local pacman at all (`aur sync -c`). Besides, you'll get all the benefits of building in chroot!

1. It is very important to review PKGBUILD (or make a conscious decision not to review it this time), so there won't be an option to disable this. But if you want an actionable review, install `vifm` — if `vifm` is present, you will be able to preview and edit all the files on the spot.

**Comment by maximbaz** [comment]
1. Honestly I've been using chroot version since the beginning, so I don't remember how the non-chroot one behaves. You don't need to worry about additional setup, aurutils will prepare everything — in fact, with chroot builds you can solve the root permission timeouts completely, see [this section](https://github.com/AladW/aurutils/blob/a13836df1da740898715cf90b45b58f5dfd15167/man1/aur-build.1#L108-L124) in `man aur-build`.

1. What you get is the contents of repo on AUR, which includes PKGBUILD + all extra files (.install files, maybe patches, some people even put some scripts there). When you don't have `vifm`, aurutils indeed shows you just the list of files so in a new terminal you can check them all for malicious contents. If I remember correctly, you can use other tools instead of `vifm` such as `ranger`, check this issue for details: https://github.com/AladW/aurutils/issues/51

**Comment by Gfurst** [comment]
While those seem reasonable, what I'm suggesting is slightly different, with regards with sudoers work around, since what I was looking is for the package **not** to be installed, as opposed to being installed automatically.

With regards for the vifm, I still think its overkill for most use cases, may I suggest that in case a file manager is not available (AUR_PAGER as it was mentioned in that thread), it could use just a plain regular EDITOR solely for PKGBUILD. Because from what I understand everything branches off that build script and usually that's the most important thing users should be checking anyway (and making alterations if they need to). That is of course only if the other methods are not available, thus why I'm suggesting as an optional configuration.

**Comment by AladW** [comment]
Packages are only installed when they are required as (make)dependencies for the build process. By default, they are removed after the build finishes (both for `aur-build` and `aur-sync`.)

**Comment by AladW** [comment]
Regarding EDITOR, that implies annoying the user with potentially hundreds of prompts (one per PKGBUILD or other important files like `.install`). Pacman wrappers may be satisfied with such an approach but it's not something I want to do.

**Comment by AladW** [comment]
Some closing remarks: `vim` works as AUR_PAGER too, using `netrw`. Same for `emacs` using `dired`. Other editors are a waste of time so that covers everything. :slightly_smiling_face: 

`aur-build` also has `--nosync` (implied by `--chroot`) if you want to perform no `pacman` operations.
