### ISSUE TITLE
aur vercmp-devel auto cache population

### ISSUE THREAD

**Issue by alexheretic** [AladW/aurutils#467]
Thank you for the _Populating the cache_ documentation in `vercmp-devel`. I was left wondering why this couldn't be handled automatically (at least to a certain extent) when `aur vercmp-devel` is executed to handle missing cache directories.

This way more complex problems, like package upstream source changes, can be addressed by clearing the cache and re-running `aur vercmp-devel`.

**Comment by maximbaz** [comment]
Because downloading sources requires you to review the sources, and making `aur vercmp-devel` open file manager like `aur sync` is definitely out of scope for `vercmp-devel`.

More complex problems, like source changes, can be addressed by `aur repo --list | cut -f1 | aur sync` 😉 Make an alias if you are planning to use this often.

**Comment by alexheretic** [comment]
Ok fair enough
