### ISSUE TITLE
aur-build: --pkgver fails to account --ignorearch

### ISSUE THREAD

**Issue by BrainDamage** [AladW/aurutils#536]
skimming the code:
https://github.com/AladW/aurutils/blob/master/lib/aur-sync#L116
--ignore-arch makes the option flag be appended to makepkg_args / makechrootpkg_makepkg_args

which then are used to call aur-build
https://github.com/AladW/aurutils/blob/master/lib/aur-sync#L298

the problem is executing --pkgver
https://github.com/AladW/aurutils/blob/master/lib/aur-build#L214
which ignores all the makepkg flags passed in the command line, including --ignorearch

As I understand, passing arbitrary flags to that command might clash with the purpose. However, for how much ugly it is, the specific flag --ignorearch should be passed through if called; otherwise makepkg->aur-build->aur-sync will fail with:

`==> ERROR: <pkgname> is not available for the '$ARCH' architecture.`

**Comment by AladW** [comment]
For `makepkg` and `makechrootpkg` builds you could do this, e.g.
```
for arg in "${makepkg_args[@]}" "${makechrootpkg_args[@]}"; do
    case $arg in
        --ignorearch|-A)
            makepkg_pre_args+=(--ignorearch); break ;;
    esac
done
```
That doesn't account for `--build-command` though, where the above implies something like: `(1)`
```
aur build --build-command my_cmd --pkgver -- -A # makepkg_args=(-A)
```
For regular builds outside of `aur-sync`, `--` resets the whole `makepkg_args` so you'd have the following command-line: `(2)`
```
aur build --pkgver -- -Acs # makepkg_args=(-Acs)
```
----
You could instead handle makepkg arguments for `--pkgver` specifically, e.g. `(3)`
```
aur build --build-command my_cmd --pkgver --pkgver-arg -A
```
or `(4)`
```
aur build --pkgver --pkgver-arg -A
```
for regular builds. This is arguably more clumsy than using `--`, though you don't need to remember the default `makepkg_args` in `aur-build`.

----
Perhaps `--` should simply *append* makepkg arguments, rather than reset them. The default set of arguments would be then reduced to `(-s)`. Not sure on a case where you'd use `makepkg` without `-s` in `aur-build`, but not everyone might want `-c`. Implying:
```
aur build --pkgver -- -A # makepkg_args=(-As)
```
