### ISSUE TITLE
aur-x86_64-build not found when running aur build -c

### ISSUE THREAD

**Issue by ljdwigney** [AladW/aurutils#624]
Testing on the aurutils-git PKGBUILD, aur build -c fails with 

`==> ERROR: build: aur-x86_64-build: command not found`

Commit 9e709249b6c23465729056bc1edcf36748263b74 adds the relevant code that's caused the issue. Devtools is installed and at the latest packaged version. A look through the filesystem shows there's no program by the name of aur-x86_64-build installed.

I noticed that there's a way to set a custom prefix, so I can set it to for example extra so extra-x86_64-build is called and change some other stuff to make it work, however I'm confused then to why the default prefix is "aur". Am I just miss-reading the documentation? I didn't see any documentation noting that the prefix _must_ be changed but then I'm unsure of why the default prefix is for a program that isn't installed? All optional-deps are installed.

**Comment by maximbaz** [comment]
https://github.com/AladW/aurutils/blob/ffc08900adee4f8771f2bb5be5093a5663047895/man1/aur-build.1#L128-L142

But I agree, @AladW @rafasc this is not ideal that aurutils simply crashes in the middle of the run. Even grepping in the aurutils repo for `aur-x86_64-build` returns nothing, because one must know to search for `aur\-x86_64\-build`.

Personally I just created these symlinks, I assume many people will do the same:

```
/usr/local/bin/aur-x86_64-build -> /usr/bin/archbuild
/usr/share/devtools/pacman-aur.conf -> /etc/pacman.conf
```

How about we make aurutils automatically fallback to `/usr/bin/archbuild` and `/etc/pacman.conf` if `/usr/local/bin/aur-x86_64-build` and `/usr/share/devtools/pacman-aur.conf` do not exist?

**Comment by AladW** [comment]
I would have added such a fallback, unfortunately archbuild cannot be
used directly:

 ==> Creating chroot for [archbuild] (archbuild)...
 setarch: archbuild: Unrecognized architecture
 ==> ERROR: Aborting...

It relies on a symbolic link pointing to it containing both the prefix
(pacman-<prefix>.conf) and the architecture (makepkg-<arch>.conf).
devtools contains extra-x86_64-build, which uses
/usr/share/devtools/pacman-extra.conf and
/usr/share/devtools/makepkg-x86_64.conf. Note that pacman-extra.conf
contains no local repositories, and any custom changes are undone on
devtools upgrade due to these files not being in the backup array of the
Arch PKGBUILD.

I've thought on adding an aur-x86_64-build link to the aurutils package,
but then we'd need to add a dependency on devtools to not have a broken
symlink, unwilling (and ostensibly most others, see #623) to do. An
instructive message in the aurutils .install file, informing users that
chroot builds require both the devtools package and the creation of a
symlink, might be a reasonable option. (In aurutils <=2.3, not having
devtools installed resulted in a similar problematic due to the
makechrootpkg/mkarchroot commands not being found in PATH.)

More generally:

From a user standpoint, the new devtools approach is strictly inferior
to aur-chroot. The new approach has the obvious benefit that we're no
longer responsible for any devtools issues. A compromise is create a new
script that only uses makechrootpkg, and no other devtools programs
(part of the reason for removing aur-chroot were issues with hardcoded
behavior in arch-nspawn). Besides working "out of the box" like
aur-chroot, such a script could better support special cases like the
temporary repository idea @Foxboron proposed. Maybe this could be an
opportunity to revive the aurutils-plugins repository, cc. @jrudess, or
some new repository like aurutils-extras. Or I could just add some
things to my dotfiles. 乁║ ˙ 益 ˙ ║ㄏ

**Comment by bartoszek** [comment]
@ljdwigney @AladW I've also get confused with the same error [#596](https://github.com/AladW/aurutils/issues/596#issuecomment-538856644) 
Perhaps there could be a direct mention of relevant manual section for user that just update `aurutils` and their current configuration stops working. New user will naturally got through the manual, but current users clearly gets confused with this error message... :thinking:

**Comment by AladW** [comment]
Yes, as I said there'd be an install message.

**Comment by bartoszek** [comment]
`install message` can got unnoticed, perhaps we could utilize `changelog=xxx` feature in PKGBUILD, this would be a nice way of introducing new features and prerequisites, and a got to place to divert users having a similar issues.

**Comment by AladW** [comment]
I have no interest in adding that myself. Patches welcome.

**Comment by AladW** [comment]
As it seems the only change needed was adding a newline to `NEWS.md`, and moving it to `aurutils.changelog`. 

#632
