### ISSUE TITLE
Please enable the Wiki

### ISSUE THREAD

**Issue by Strykar** [AladW/aurutils#646]
The Github wiki could be a place for practical examples for beginners and a repository for gems like https://github.com/AladW/aurutils/issues/641
It might also save you having to read some [painful reddit threads](https://www.reddit.com/r/archlinux/comments/dzm6h1/understanding_aurutils_setting_up_an_easytouse/) on aurutils usage :)

**Comment by rafasc** [comment]
What problem are we trying to solve with having a github-wiki? Ease of access to a rendered version of the documentation we already have? Ease contributions from people who don't grok groff?

I am not strictly against having the wiki, but we already have some examples on `aur(1)`, such onliner could be easily added there. 
We also already host "how-to" manuals, `aurvcs(7)` and `aurhosting(7)`. Do we have significant content to justify another source of documentation, that doesn't fit in one of the above cases?

**Comment by Strykar** [comment]
It is unlikely that folks who don't grok groff, would find themselves contributing to a GH wiki.

But to non-programmers (like me) and new arch users, a step-by-step howto would be welcome.
The misinformation on reddit threads is evidence of this.

A common response to the suggestion of using aurutils on #archlinux is that it isn't install-and-go friendly as some of the alternatives. I'm not suggesting it should be, I'm suggesting the documentation could be.

Or are you/Alad against an Archlinux wiki style form of documentation to get aurutils up, running and working with examples and tips for outlier situations?
The idea is definitely not to post the man pages here, it's unclear where you got that idea.

It might offer a chance at an alternative attempt of documentation which is friendlier than the terse examples in the man pages. I don't see how this could be a bad thing?

**Comment by rafasc** [comment]
> It is unlikely that folks who don't grok groff, would find themselves contributing to a GH wiki.
> 
> But to non-programmers (like me) and new arch users, a step-by-step howto would be welcome.
> The misinformation on reddit threads is evidence of this.
> 
The misinformation on reddit is not exclusively about how aurutils works. Many are coming from misunderstandings of fundamental concepts like what is a pacman repo, what are foreign packages, etc. Clarifying such concepts would be something we would want on the archwiki, not ours.

> A common response to the suggestion of using aurutils on #archlinux is that it isn't install-and-go friendly as some of the alternatives. I'm not suggesting it should be, I'm suggesting the documentation could be.
> 

aurutils follows ArchLinux principles and assumes the user knows and is capable of configuring their machine. See [FAQ](https://wiki.archlinux.org/index.php/Frequently_asked_questions#I_am_a_complete_GNU/Linux_beginner._Should_I_use_Arch?)

Since users should be familiar with packaging/repos before venturing into any kind of aur helper, and the setup is essentially two simple steps, (Creating a local repo and adding an entry to pacman.conf), it **is** pretty much install and go if you consider those two step part of the install.

But aurutils is so different from other aur helpers that even if you did automate those steps you would still get "complaints" that it isn't "install and go"; because they installed and `aur -Syu` didn't work.

The "warning" is mostly a heads up saying that aurutils uses a completely different approach from other aur helpers.

> Or are you/Alad against an Archlinux wiki style form of documentation to get aurutils up, running and working with examples and tips for outlier situations?

I don't know if Alad cares about (re?)-opening the wiki. I am not strictly against it but, in my opinion, any improvements could be applied to the current documentation without introducing yet another thing we need to maintain up to date.

> The idea is definitely not to post the man pages here, it's unclear where you got that idea.
> 

Some projects use it in restricted mode to host documentation. And I have looked into this in the recent past since GitHub doesn't provide rich view for groff (there's only some syntax highlight). I was thinking in making a branch with html/markdown docs generated from the man pages we have, mostly for viewing convenience on the web. But using the wiki in restricted mode could be another way to do it.

> It might offer a chance at an alternative attempt of documentation which is friendlier than the terse examples in the man pages. I don't see how this could be a bad thing?

My point is that such guides and/or improvements would be equally useful to have as man pages.

Don't let this discourage you. Writing the guide's content is the hard part. If you want to give it a try but need help with groff, feel free to ping me on IRC.

**Comment by AladW** [comment]
I agree with the comment by @rafasc:

> I am not strictly against it but, in my opinion, any improvements could be applied to the current documentation without introducing yet another thing we need to maintain up to date.

A wiki implies someone monitoring it, and I don't really have the time for that.

**Comment by Strykar** [comment]
@rafasc I'll ping you on IRC. @AladW Thanks for chiming in, closing.
