### ISSUE TITLE
aurcheck: retrieve new pkgver for VCS packages

### ISSUE THREAD

**Issue by AladW** [AladW/aurutils#65]
Old approach: https://github.com/AladW/aurutils/blob/1eb2271bae5b87c582104e81f52a19d642b401ce/aursync#L52

Which was hacked, as you have to install packages outside `makepkg -s` and hardcode VCS. Running pkgver() a second time isn't very nice either.

**Comment by rmarquis** [comment]
Note that you can technically rely on the VCSCLIENTS array of makepkg.conf if you want to avoid hardcoding VCS clients.

**Comment by AladW** [comment]
Finding VCS packages in a given list could have its place in aurqueue.

**Comment by AladW** [comment]
I've left an attempt in the experimental branch for now. For the needed glue with other scripts, see #79.

**Comment by AladW** [comment]
@vodik's script:

https://ptpb.pw/qBwa/bash

**Comment by vodik** [comment]
I think @holomorph did some work on this stuff too, if you poke him nicely on IRC.

**Comment by holomorph** [comment]
I looked into it a bit, but I think @Earnestly figured this out more thoroughly. I never committed my rebuild script to any repo and don't have access to that machine atm

**Comment by Earnestly** [comment]
Ah but I only support git (for now) and don't support (or rely, however you want to look at it) on the PKGBUILDs: https://github.com/Earnestly/pkgbuilds/blob/master/util.bash

It's allows me to keep it -very- simple because I don't exactly need that level of dynamic convenience which is necessary for a project like this.

**Comment by AladW** [comment]
For more suggested workarounds, see #227.

**Comment by AladW** [comment]
For an interesting approach which uses the github API (github.com sources only), see:

https://github.com/Jguer/yay/blob/a6a0b9b441e3bdc67a9ac9f86c2961956531c31b/vcs.go

**Comment by maximbaz** [comment]
@AladW I noticed this issue has an `upstream` label, I assume it is referring to [FS#56602](https://bugs.archlinux.org/task/56602)? If so, the consensus seems to be to use naming conventions for packages.

But also, I noticed that the discussion there is about how to detect which packages are VCS and VCS-like, not about how to detect if a package actually has an update. To me it sounds that the more complicated part is actually invoking `pkgver()` and detecting whether a given package needs to be updated or not, and it isn't as much of a big a deal to decide _when_ to run this check - we could start with the most simple implementation possible (match package name against hardcoded list of suffixes?) and later improve.

Therefore the question: are you planning on revisiting this issue? 🙂 I'm asking because to me personally, coming from `yay` the lack of support for upgrading VCS packages seems like the biggest drawback of `aurutils`.

**Comment by AladW** [comment]
I would propose to start a discussion on aur-general regarding a naming convention. If there's some form of consensus something can be added to the wiki.

As to the implementation, the main issue is that with regular packages, you can simply retrieve the version from the RPC before sourcing the PKGBUILD; with VCS packages it's the other way around, assuming the use of `makepkg --verifysource`.

**Comment by maximbaz** [comment]
I see, and how would one make use of `makepkg --verifysource`, parse stdout and grep for `master -> master`? Sounds hacky, and the default branch isn't necessarily called `master`, but I don't see any other visible side-effects...

**Comment by AladW** [comment]
I wouldn't parse stdout in this case, but rather run `makepkg --printsrcinfo` afterwards, mangle the output to a full version string, and use that for comparison purposes.

**Comment by maximbaz** [comment]
Ah but `makepkg --printsrcinfo` still reports the old version, I think it generates it out of PKGBUILD which itself still has the old version, and I think PKGBUILD updates the pkgver (the field) only when you actually build the package and not earlier.

**Comment by AladW** [comment]
Yes you seem to be right that `makepkg --verifysource` doesn't actually run `pkgver`. Looking at the [old code](https://github.com/AladW/aurutils/blob/1eb2271bae5b87c582104e81f52a19d642b401ce/aursync#L52), it used `makepkg -od --noprepare` to run pkgver().

There's also the issue when e.g. `git` is not installed on the user system but run in pkgver(). So you'd need to look at the protocol in .SRCINFO and possibly install it afterward on the user system.

**Comment by maximbaz** [comment]
This works! So what do you think about starting with something simple, excluding VCS-likes and doing this check for packages that end with `-bzr|-git|-hg|-svn`? For the rest, RPC call as today. If yes, do you want to do this yourself, do you want me to make a PR?

> There's also the issue when e.g. git is not installed on the user system but run in pkgver(). So you'd need to look at the protocol in .SRCINFO and possibly install it afterward on the user system.

In a valid PKGBUILD `git` must be defined in `makedepends`, the solution is simply to use `makepkg -os --noprepare` and this will install missing makedepends if they have been removed. After we discussed the other issue earlier today, I actually rebuilt all AUR packages that I use in chroot and reported to a couple of VCS packages that they must specify `git` in the `makedepends` array (but most of them do).

**Comment by AladW** [comment]
`makepkg -os` does sound like a better idea than trying to copy makepkg poorly. Feel free to work on it! I may take a look at the code later.

**Comment by AladW** [comment]
Rudimentary support has been provided through `aur-srcver` and a "file" mode in `aur-vercmp`. Remaining discussion is done in #283 and #286.
