### ISSUE TITLE
Missing pacman-aur.conf used in aur chroot

### ISSUE THREAD

**Issue by johnramsden** [AladW/aurutils#783]
Recently `aurutils` (when used in chroot) started failing with the following message:

> chroot: config file /usr/share/devtools/pacman-aur.conf could not be read

This file does not exist on my system. Do I need to create it? Should it be there?

[aurutils.log](https://github.com/AladW/aurutils/files/5483985/aurutils.log)

**Comment by AladW** [comment]
Please read the changelog.

**Comment by AladW** [comment]
https://pkgbuild.com/~alad/aurutils_3.html#mozTocId493532

**Comment by CarbonChauvinist** [comment]
> aur-build defaults to --suffix=aur, or /usr/share/devtools/pacman-aur.conf; you should configure the local repository here.

Can you clarify these instructions please? Does this simply mean I can copy my existing `/etc/pacman.conf`, which has my local repo configured, over to `/usr/share/devtools/pacman-aur.conf`? Or are there specific rules for what is expected in that file? 

For instance would it be better to copy `/usr/share/devtools/pacman-extra.conf` to `/usr/share/devtools/pacman-aur.conf` and add my custom repo to the newly copied file?

I do see that you're planning on moving this config out of /usr and into `/etc/aurutils/pacman-<db>.conf` in a future release, which I personally like. Thanks for sharing this project with us.

**Comment by AladW** [comment]
I will update my blog for 3.1.0. Bottom-line it's indeed best to copy /usr/share/devtools/pacman-extra.conf (now to /etc/aurutils/pacman-<your repo>.conf) because /etc/pacman.conf might contain some conflicting directives like `IgnorePkg`. Also `Include` is not processed by devtools so you should write any additional repositories like `[multilib]` and your local repo explicitely in the configuration file.
