### ISSUE TITLE
aur-sync.1: extend DESCRIPTION

### ISSUE THREAD

**Issue by AladW** [AladW/aurutils#844]
On IRC it was suggested to describe in greater detail what tasks `aur-sync` performs. Specifically include the following summary:
```
What aur-sync does, roughly speaking, is:

* resolve AUR dependencies with aur-depends;
* retrieve (or update) the results as git repositories with aur-fetch;
* print diffs if there were changes (e.g. after an AUR update);
* show all of these in a file manager;
* build the packages with aur-build.
```
https://bbs.archlinux.org/viewtopic.php?pid=1934454#p1934454

**Comment by AladW** [comment]
> How users might plug the gaps by using the aur- utils along with aur-sync might be worth exploring too.

With `aur-view`, it's much easier to keep the `aur-sync` UI and adapt it to custom workflows. See #860, #840, #953. Eventually this might result in am `aurworkflows(7)` man page.

**Comment by AladW** [comment]
Please review https://github.com/AladW/aurutils/pull/954

**Comment by Earnestly** [comment]
The semi-colons aren't needed and the bullet puts could be capitalised, but otherwise I think it's fine for explaining how aur-sync is composed.  One other nit is that the SYNOPSIS includes single-opt flags which aren't entirely represented in the OPTIONS section, e.g. there is no `-A`, or `-g` and so on.

**Comment by AladW** [comment]
Good points, updated.
