### ISSUE TITLE
Whats up with all the interface changes

### ISSUE THREAD

**Issue by rien333** [AladW/aurutils#883]
Whats up with all the interface changes (even between 3.0, 3.1, and 3.2)? As someone who uses `aurutils` for a very particular purpose and doesn't really care about all its antics and tbh overly extreme complexities, its pretty annoying that I have to (i) rewrite my scripts every few months (ii) learn to parse and  read the man pages all over again. 

Most tools are way more stable in their cli interface. Why does `aurutils` choose not to be? What about gradually deprecating cli flags instead, or at least intelligently warning users about changes?

Let me give an example.

I have these two lines in a script: 

```
repo_path=$(dirname $(aur repo --path-list))
repo-remove $(aur repo --path) "$@"
```

If you don't know what this is supposed to do, that makes two of us. (I had an idea a a few months ago, but I really don't anymore)

**Comment by rien333** [comment]
Sorry if this comes of as shitty, but I ultimately want to give some feedback from someone who's more of an outsider.

**Comment by AladW** [comment]
I barely make interface changes at all, and when I do there's a good reason for them. In either case, there's plenty of time to update - between 3.1.2 and 3.2.0 there was about 1 year. Furthermore, every release has a detailed changelog which is even part of the aurutils pacman package. 

If you don't want to change anything even after that time, keep using the old version - the APIs aurutils uses have changed rarely (if ever) since its first release, and I've heard reports of people still using 1.5.3. The one exception is pacsift, which since pacman 6 requires `unbuffer` to run in shell pipes.

I won't go into more specifics since the premise of this report made me lose interest very quickly. If you want to file a less weighed report about specifics of the aur-repo interface, feel free.

On Thu, 23 Dec 2021 06:32:08 -0800
Rijnder Wever ***@***.***> wrote:

> Whats up with all the interface changes (even between 3.0, 3.1, and 3.2)? As someone who uses `aurutils` for a very particular purpose and doesn't really care about all its antics and tbh overly extreme complexities, its pretty annoying that I have to (i) rewrite my scripts every few months (ii) learn to parse and  read the man pages all over again. 
> 
> Most tools are way more stable in their cli interface. Why does `aurutils` choose not to be? What about gradually deprecating cli flags instead, or at least intelligently warning users about changes?
> 
> Let me give an example.
> 
> I have these two lines in a script: 
> 
> 
> ```
> repo_path=$(dirname $(aur repo --path-list))
> repo-remove $(aur repo --path) "$@"
> ```
> 
> If you don't know what this is supposed to do, that makes two of us. (I had an idea a a few months ago, but I really don't anymore)
> 
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/AladW/aurutils/issues/883
> You are receiving this because you are subscribed to this thread.
> 
> Message ID: ***@***.***>


-- 
alad ***@***.***>

**Comment by AladW** [comment]
Since it was little work, I've added some compatibility options with #886

I'm also considering dropping semver so people don't get unrealistic expectations.
