### ISSUE TITLE
Is it possible to run 'aur sync -u' without it running pacman?

### ISSUE THREAD

**Issue by TN-1** [AladW/aurutils#897]
Essentially, the behaviour I am after is to run 'aur sync -u' and have it go through, do the updates and just apply them to the custom repo, but not install them. At the moment, I can 'Ctl+C' when sudo asks for my password, but I would like to find out if there is a proper solution to this.  
Thanks

**Comment by Earnestly** [comment]
Dependencies which get updated need to be available for subsequent builds in the chain that depend on those packages.  I'm not sure what you're expecting in this scenario.

**Comment by AladW** [comment]
Indeed, and this holds true regardless of whether you use a local repo or not. Since the main concern seems to be about entering the sudo password, I'd suggest `NOPASSWD` entries for pacman, preferably with a seperate user. This is documented in `man aur build` under the `Using a dedicated build user` section.
