### ISSUE TITLE
aur build --results will be removed in the next release. If someone still uses this flag, please let me know.

### ISSUE THREAD

**Issue by Cody-Learner** [AladW/aurutils#980]
Alad posted [title] in the Arch forum. https://bbs.archlinux.org/viewtopic.php?pid=2030103#p2030103

I use 'aur build --results' in my AUR helper script: https://github.com/Cody-Learner/aurch/blob/main/aurch#L193

IIRC, I added using 'aur build --results' option when rebuilding and replacing an existing package of the same version. https://github.com/Cody-Learner/aurch/commit/e7ba9043e36e17750ac0a394915bd019e197759b#diff-d69b38f1349d2dbaaea7cebe2dfc90e678a800a00c33791f3424b2b343b51c38L191

Is there any possibility to keep it as is or an alternative way to get similar output?

Is there a results file printed to a default location, and "--results" just redirects the output?

Also just noticed '--results' has been removed from the latest man page.

**Comment by AladW** [comment]
Thanks for providing your use case. I can keep it around in the foreseeable future, sure. The reasons I considered it for removal is that it doesn't play well with some features I've added, namely:

1. aur-sync--ninja which results in a one aur-build call per package (such that --results would only contain an entry for the last package in the queue)
2. root support / privilege drop support for aur-build, where --results would write as root.

I haven't studied your code in detail yet, but one possible replacement is aur-build --dry-run. That option also includes the pkgbase in the output. However, it is quite a bit slower than --results since it runs aur build--pkglist for every package.

aur-build --results has no default file. The output is only printed when the option is defined, see https://github.com/AladW/aurutils/blob/master/lib/aur-build#L444-L446


On Wed, 06 Apr 2022 11:49:09 -0700
Cody Learner ***@***.***> wrote:

> Allad posted [title] in the Arch forum. 
> 
> I use 'aur build --results' in my AUR helper script: https://github.com/Cody-Learner/aurch
> 
> IIRC, I added using '--results' in place of parsing makepkg output, as a cleaner method.
> 
> IS there any possibility to keep it as is or an alternative way to get similar output?
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/AladW/aurutils/issues/980
> You are receiving this because you are subscribed to this thread.
> 
> Message ID: ***@***.***>


-- 
alad ***@***.***>

**Comment by AladW** [comment]
I addressed the issues outlined above in the `build-results-append` branch. Please give it a test.

**Comment by Cody-Learner** [comment]
Very cool and thank you! 

I've got to get some work done outside while it's still daylight at the moment. 
I'll do some testing with the build-results-append branch this evening and provide some feedback asap.

What would be the best way to install this for testing? Edit the aurutils pkgbuild file to build and install, or possibly just manually overwrite the aur-build and whatever other changed files?

**Comment by AladW** [comment]
The fastest approach is to git-checkout the build-results-append branch, and run 

export AUR_EXEC_PATH=<path to aurutils clone>/lib

but either way works

On Wed, 06 Apr 2022 14:34:37 -0700
Cody Learner ***@***.***> wrote:

> Very cool and thank you! 
> 
> I've got to get some work done outside while it's still daylight at the moment. 
> I'll do some testing with the build-results-append branch this evening and provide some feedback asap.
> 
> What would be the best way to install this for testing? Edit the aurutils pkgbuild file to build and install, or possibly just manually overwrite the aur-build and whatever other changed files?
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/AladW/aurutils/issues/980#issuecomment-1090831070
> You are receiving this because you commented.
> 
> Message ID: ***@***.***>


-- 
alad ***@***.***>

**Comment by Cody-Learner** [comment]
Seems the "build-results-append" branch works well with my script (limited to one test package). Same results as the current version.

I don't think further testing is warranted because I verified the 'aur build --results' file is present and the contents are correct.

My testing was ran with aur-build (md5sum 0036a8f03eb686b5f91b33d3bc3fe884).

**Comment by AladW** [comment]
Great, merged to `master` :+1:

**Comment by AladW** [comment]
Hey @Cody-Learner 

With e337c571e940bd1ea1cb1afe1f125d3cd5e3ae18 I added `exist:...` entries to the `--result` output, if some package is already built. 

As such I recommend to check for `build:` entries explicitly, e.g.
```
awk -F: '$1 ~ /^build$/ { ... }
```

**Comment by Cody-Learner** [comment]
Hey @AladW 

Really appreciate you adding this last post a few years ago.  I'm currently looking into this with some testing.

Working on my AUR script https://github.com/Cody-Learner/aurch which builds and wraps nspawn and aurutils in a container using aurutils commands aur depends, fetch, build. 

My script is basically getting aur build depends and ordering from aurutils, then I loop through the data, feeding it to aur build. Moving packages from container to host, pacman db related stuff,  and whatever else is done by my script.

I'd really like to get away from parsing 'aur build's' raw output though. Although it's proven reliable over the test of time on my systems, that doesn't make it any better a method.

Seems the 'aur build --results=file' was the perfect solution but not sure how to get it working for my use case....

During testing, I have an aur pkg available already in aur sync db., and rebuilding it using 'aur build -f' as a test case. It shows up in aur build output as: "==> 'WARNING: An entry for 'bauerbill-2021.12.31-14' already existed", but not in the 'aur build --results=file' as 'exists:file:......pkg'. The results file does contain 'build:file:.....pkg', but I was expecting 'exists:' as well.

Are the results I'm getting using the '-f force' flag?  Better yet here's the entire command to be clear:

    aur build -fnsr --margs -C --results=aur-build-raw.log

Would the package have to be installed to be listed as 'exists:' in 'aur build --results=file'?    Seems unlikely though...
Do I need to configure my local aur db's somewhere in aurutils for it see them for 'aur build --result=file' 'exists:' output?

I'd really like to use 'exists:' to replace my current parsing of '==> 'WARNING....' from 'aur build's' output, which is used to tell my script to reinstall the package and re-enter it in the db. 

That is if it's printed to the '--results=file' for the same or similar conditions as in the output as '==> 'WARNING....'.

**Comment by AladW** [comment]
With the `-f` flag, the package is going to be rebuilt no matter what - hence the `build:` entry. The check itself is performed using (the equivalent of) `makepkg --packagelist` on your local repository path:
```
PKGDEST="$db_root" ${AUR_BUILD_PKGLIST:-aur build--pkglist} "${makepkg_pkglist_args[@]}"
```
Without `-f`, the existing package(s) will be passed on to `repo-add`: issue #838. (An extreme example is that the local repository is removed, but the packages remain.)

In both cases, the `WARNING: An entry already existed` message is from `repo-add` - even when you rebuild the package with `-f`, the `pkgver` and `pkgrel` will be the same. Rebuilt packages are typically different, e.g. when linking against different dependencies, so it's advisable to bump `pkgrel` in that case so that `pacman -Syu` will pull in the new package. See `examples/sync-rebuild` for some possible approaches.
